# -*- coding: utf-8 -*-
"""英語の語順トレーナー：文データ生成＆検証"""
import json, re, sys

def b(en, jp, role): return {"en": en, "jp": jp, "role": role}

S = []  # level, pattern, en, blocks, jp(natural), point, explain

# ===== 基本 (18) =====
S += [
{"level":"基本","pattern":"主語+動詞+目的語","en":"I play tennis.",
 "blocks":[b("I","私は","主語"),b("play","する","動詞"),b("tennis","テニスを","目的語")],
 "jp":"私はテニスをする。","point":"動詞→目的語の順",
 "explain":"日本語は「テニスを→する」。英語は「する→テニスを(play tennis)」で、動詞が先・目的語が後ろ。"},
{"level":"基本","pattern":"主語+動詞+目的語","en":"I read a book.",
 "blocks":[b("I","私は","主語"),b("read","読む","動詞"),b("a book","本を","目的語")],
 "jp":"私は本を読む。","point":"動詞→目的語",
 "explain":"「本を→読む」が英語では「read→a book」。動詞が先、目的語が後ろ。"},
{"level":"基本","pattern":"主語+動詞+目的語","en":"I like dogs.",
 "blocks":[b("I","私は","主語"),b("like","好きだ","動詞"),b("dogs","犬が","目的語")],
 "jp":"私は犬が好きだ。","point":"「好き」も動詞、対象は後ろ",
 "explain":"「犬が→好き」→英語は「like→dogs」。like(好き)を先に置くのがコツ。"},
{"level":"基本","pattern":"3単現のs","en":"She speaks English.",
 "blocks":[b("She","彼女は","主語"),b("speaks","話す","動詞"),b("English","英語を","目的語")],
 "jp":"彼女は英語を話す。","point":"3人称単数は動詞にs",
 "explain":"主語が She なので speak に s。並びは〈主語→動詞→目的語〉のまま。"},
{"level":"基本","pattern":"3単現のs","en":"He watches TV.",
 "blocks":[b("He","彼は","主語"),b("watches","見る","動詞"),b("TV","テレビを","目的語")],
 "jp":"彼はテレビを見る。","point":"-chで終わる動詞は-es",
 "explain":"watch→watches。順番は「見る→テレビを(watches TV)」。"},
{"level":"基本","pattern":"動詞+目的語+時","en":"I drink coffee every morning.",
 "blocks":[b("I","私は","主語"),b("drink","飲む","動詞"),b("coffee","コーヒーを","目的語"),b("every morning","毎朝","時")],
 "jp":"私は毎朝コーヒーを飲む。","point":"時は文の最後",
 "explain":"「毎朝→コーヒーを→飲む」→英語は「drink→coffee→every morning」。時が最後にくる。"},
{"level":"基本","pattern":"動詞+目的語+時","en":"I study English every day.",
 "blocks":[b("I","私は","主語"),b("study","勉強する","動詞"),b("English","英語を","目的語"),b("every day","毎日","時")],
 "jp":"私は毎日英語を勉強する。","point":"時は文末",
 "explain":"日本語は時が前(毎日)。英語は〈動詞→目的語→時〉で every day が最後。"},
{"level":"基本","pattern":"be動詞+補語","en":"I am a student.",
 "blocks":[b("I","私は","主語"),b("am","です","動詞"),b("a student","学生","補語")],
 "jp":"私は学生です。","point":"be動詞「です」も動詞の位置",
 "explain":"「学生→です」→英語は「am→a student」。be動詞(am/is/are)は主語の直後。"},
{"level":"基本","pattern":"be動詞+形容詞","en":"He is kind.",
 "blocks":[b("He","彼は","主語"),b("is","だ","動詞"),b("kind","親切","補語")],
 "jp":"彼は親切だ。","point":"be+形容詞=「~だ」",
 "explain":"「親切→だ」→英語は「is→kind」。is が先、形容詞が後ろ。"},
{"level":"基本","pattern":"be動詞+補語(複数)","en":"They are teachers.",
 "blocks":[b("They","彼らは","主語"),b("are","だ","動詞"),b("teachers","先生","補語")],
 "jp":"彼らは先生だ。","point":"複数主語は are",
 "explain":"They→are。「先生→だ」が「are→teachers」。"},
{"level":"基本","pattern":"be from(出身)","en":"I am from Japan.",
 "blocks":[b("I","私は","主語"),b("am","だ","動詞"),b("from Japan","日本出身","場所")],
 "jp":"私は日本出身だ。","point":"be from ~=「~出身」",
 "explain":"「日本→出身」→英語は「am→from Japan」。from が場所の前にくる。"},
{"level":"基本","pattern":"go to+場所","en":"I go to school.",
 "blocks":[b("I","私は","主語"),b("go","行く","動詞"),b("to school","学校へ","場所")],
 "jp":"私は学校へ行く。","point":"「~へ」は to+場所(動詞の後)",
 "explain":"「学校へ→行く」→英語は「go→to school」。動詞が先、to+場所が後ろ。to=「~へ」。"},
{"level":"基本","pattern":"go home(副詞)","en":"I go home.",
 "blocks":[b("I","私は","主語"),b("go","帰る","動詞"),b("home","家に","場所")],
 "jp":"私は家に帰る。","point":"home は副詞、to は不要",
 "explain":"「家に帰る」は go home。home は「家に」を表す副詞なので to を付けない（×go to home）。"},
{"level":"基本","pattern":"live in+場所","en":"I live in Tokyo.",
 "blocks":[b("I","私は","主語"),b("live","住んでいる","動詞"),b("in Tokyo","東京に","場所")],
 "jp":"私は東京に住んでいる。","point":"「~に住む」は live in+場所",
 "explain":"「東京に→住む」→英語は「live→in Tokyo」。in が場所の前。"},
{"level":"基本","pattern":"動詞+at+時刻","en":"I get up at seven.",
 "blocks":[b("I","私は","主語"),b("get up","起きる","動詞"),b("at seven","7時に","時")],
 "jp":"私は7時に起きる。","point":"時刻は at+時(動詞の後)",
 "explain":"「7時に→起きる」→英語は「get up→at seven」。at が時刻の前にくる。"},
{"level":"基本","pattern":"動詞+目的語+場所","en":"We play soccer in the park.",
 "blocks":[b("We","私たちは","主語"),b("play","する","動詞"),b("soccer","サッカーを","目的語"),b("in the park","公園で","場所")],
 "jp":"私たちは公園でサッカーをする。","point":"目的語→場所 の順",
 "explain":"「公園で→サッカーを→する」→英語は「play→soccer→in the park」。動詞→目的語→場所。"},
{"level":"基本","pattern":"動詞+目的語+場所","en":"She sings a song in her room.",
 "blocks":[b("She","彼女は","主語"),b("sings","歌う","動詞"),b("a song","歌を","目的語"),b("in her room","部屋で","場所")],
 "jp":"彼女は部屋で歌を歌う。","point":"目的語→場所",
 "explain":"日本語は場所が前(部屋で)。英語は「sings→a song→in her room」の順。"},
{"level":"基本","pattern":"動詞+場所","en":"I study at the library.",
 "blocks":[b("I","私は","主語"),b("study","勉強する","動詞"),b("at the library","図書館で","場所")],
 "jp":"私は図書館で勉強する。","point":"場所は動詞の後、at+場所",
 "explain":"「図書館で→勉強する」→英語は「study→at the library」。"},
]

# ===== 応用 (18) =====
S += [
{"level":"応用","pattern":"主語+動詞+目的語+場所+時","en":"I play soccer in the park every Sunday.",
 "blocks":[b("I","私は","主語"),b("play","する","動詞"),b("soccer","サッカーを","目的語"),b("in the park","公園で","場所"),b("every Sunday","毎週日曜に","時")],
 "jp":"私は毎週日曜日に公園でサッカーをする。","point":"〈主語→動詞→目的語→場所→時〉",
 "explain":"英語の基本の並び。日本語(毎週日曜に 公園で サッカーを する)と最も入れ替わる型。"},
{"level":"応用","pattern":"動詞+副詞+時","en":"I get up early in the morning.",
 "blocks":[b("I","私は","主語"),b("get up","起きる","動詞"),b("early","早く","その他"),b("in the morning","朝に","時")],
 "jp":"私は朝早く起きる。","point":"時は最後",
 "explain":"「朝→早く→起きる」→英語は「get up→early→in the morning」。時を最後に。"},
{"level":"応用","pattern":"動詞+目的語+時","en":"I have lunch at noon.",
 "blocks":[b("I","私は","主語"),b("have","とる","動詞"),b("lunch","昼食を","目的語"),b("at noon","正午に","時")],
 "jp":"私は正午に昼食をとる。","point":"時は文末、at+時",
 "explain":"「正午に→昼食を→とる」→英語は「have→lunch→at noon」。"},
{"level":"応用","pattern":"be動詞+場所","en":"The book is on the desk.",
 "blocks":[b("The book","その本は","主語"),b("is","ある","動詞"),b("on the desk","机の上に","場所")],
 "jp":"その本は机の上にある。","point":"be動詞=「ある/いる」、場所は後ろ",
 "explain":"「机の上に→ある」→英語は「is→on the desk」。on が場所の前。"},
{"level":"応用","pattern":"There is/are","en":"There is a cat under the table.",
 "blocks":[b("There is","いる","その他"),b("a cat","猫が","主語"),b("under the table","テーブルの下に","場所")],
 "jp":"テーブルの下に猫がいる。","point":"There is+主語+場所（日本語と真逆）",
 "explain":"「テーブルの下に→猫が→いる」→英語は「There is→a cat→under the table」。並びが逆になる。"},
{"level":"応用","pattern":"be動詞+時","en":"My birthday is in May.",
 "blocks":[b("My birthday","私の誕生日は","主語"),b("is","だ","動詞"),b("in May","5月に","時")],
 "jp":"私の誕生日は5月だ。","point":"時は be動詞の後、in+月",
 "explain":"「5月→だ」→英語は「is→in May」。in が月の前にくる。"},
{"level":"応用","pattern":"can+動詞","en":"I can swim well.",
 "blocks":[b("I","私は","主語"),b("can","できる","助動詞"),b("swim","泳ぐ","動詞"),b("well","上手に","その他")],
 "jp":"私は上手に泳げる。","point":"助動詞 can+動詞の原形",
 "explain":"can の後は原形 swim。「上手に泳げる」=can swim well。"},
{"level":"応用","pattern":"will+動詞+時","en":"I will visit Kyoto next week.",
 "blocks":[b("I","私は","主語"),b("will","〜する予定","助動詞"),b("visit","訪れる","動詞"),b("Kyoto","京都を","目的語"),b("next week","来週","時")],
 "jp":"私は来週京都を訪れる。","point":"will+原形、時は最後",
 "explain":"「来週→京都を→訪れる」→英語は「will visit→Kyoto→next week」。"},
{"level":"応用","pattern":"must+動詞","en":"I must do my homework.",
 "blocks":[b("I","私は","主語"),b("must","ねばならない","助動詞"),b("do","する","動詞"),b("my homework","宿題を","目的語")],
 "jp":"私は宿題をしなければならない。","point":"must+原形",
 "explain":"「宿題を→しなければ」→英語は「must→do→my homework」。助動詞の後は原形。"},
{"level":"応用","pattern":"should+動詞","en":"You should see a doctor.",
 "blocks":[b("You","あなたは","主語"),b("should","べきだ","助動詞"),b("see","診てもらう","動詞"),b("a doctor","医者に","目的語")],
 "jp":"あなたは医者に診てもらうべきだ。","point":"should+原形",
 "explain":"「医者に→診てもらうべき」→英語は「should→see→a doctor」。"},
{"level":"応用","pattern":"want to+動詞","en":"I want to be a teacher.",
 "blocks":[b("I","私は","主語"),b("want","〜したい","動詞"),b("to be","なること","動詞"),b("a teacher","先生に","補語")],
 "jp":"私は先生になりたい。","point":"want to+原形=「~したい」",
 "explain":"「先生に→なりたい」→英語は「want to be→a teacher」。「~したい(want to)」を先に。"},
{"level":"応用","pattern":"like to+動詞","en":"I like to read books.",
 "blocks":[b("I","私は","主語"),b("like","好きだ","動詞"),b("to read","読むこと","動詞"),b("books","本を","目的語")],
 "jp":"私は本を読むのが好きだ。","point":"like to+原形",
 "explain":"「本を→読むのが→好き」→英語は「like to read→books」。"},
{"level":"応用","pattern":"不定詞(目的)","en":"I went to the park to play soccer.",
 "blocks":[b("I","私は","主語"),b("went","行った","動詞"),b("to the park","公園へ","場所"),b("to play soccer","サッカーをするために","その他")],
 "jp":"私はサッカーをするために公園へ行った。","point":"to+原形=「~するために」(目的は後ろ)",
 "explain":"「サッカーをするために→公園へ→行った」→英語は「went→to the park→to play soccer」。目的が最後。"},
{"level":"応用","pattern":"疑問文(Do)","en":"Do you like music?",
 "blocks":[b("Do","〜ですか","助動詞"),b("you","あなたは","主語"),b("like","好き","動詞"),b("music","音楽が","目的語")],
 "jp":"あなたは音楽が好きですか？","point":"疑問文は Do を先頭に",
 "explain":"日本語の「~ですか?」は文末。英語は Do を文頭に置く大きな語順転換。"},
{"level":"応用","pattern":"疑問詞(What)","en":"What do you want?",
 "blocks":[b("What","何を","疑問"),b("do","―","助動詞"),b("you","あなたは","主語"),b("want","欲しい","動詞")],
 "jp":"あなたは何が欲しいですか？","point":"疑問詞→do→主語→動詞",
 "explain":"「何が→欲しい?」→英語は What を先頭に〈What→do→you→want〉。"},
{"level":"応用","pattern":"疑問詞(Where)","en":"Where do you live?",
 "blocks":[b("Where","どこに","疑問"),b("do","―","助動詞"),b("you","あなたは","主語"),b("live","住む","動詞")],
 "jp":"あなたはどこに住んでいますか？","point":"Where を文頭に",
 "explain":"「どこに→住む?」→英語は〈Where→do→you→live〉。疑問詞が文頭。"},
{"level":"応用","pattern":"疑問文(Can)","en":"Can you play the guitar?",
 "blocks":[b("Can","〜できますか","助動詞"),b("you","あなたは","主語"),b("play","弾く","動詞"),b("the guitar","ギターを","目的語")],
 "jp":"あなたはギターを弾けますか？","point":"助動詞 Can を先頭に",
 "explain":"「ギターを→弾けますか?」→英語は Can を先頭に〈Can→you→play→the guitar〉。"},
{"level":"応用","pattern":"比較級","en":"Ken is taller than Tom.",
 "blocks":[b("Ken","ケンは","主語"),b("is","だ","動詞"),b("taller","より背が高い","補語"),b("than Tom","トムより","その他")],
 "jp":"ケンはトムより背が高い。","point":"比較級+than ~",
 "explain":"「トムより→背が高い」→英語は「taller→than Tom」。比較級が先、than が後ろ。"},
]

# ===== 発展 (12) =====
S += [
{"level":"発展","pattern":"最上級","en":"This is the most interesting book.",
 "blocks":[b("This","これは","主語"),b("is","だ","動詞"),b("the most interesting","最もおもしろい","その他"),b("book","本","補語")],
 "jp":"これは最もおもしろい本だ。","point":"最上級 the most+形容詞（名詞の前）",
 "explain":"「最もおもしろい→本」→英語は「the most interesting→book」。形容詞のかたまりが名詞の前。"},
{"level":"発展","pattern":"SVOO(人+物)","en":"I gave him a present.",
 "blocks":[b("I","私は","主語"),b("gave","あげた","動詞"),b("him","彼に","目的語"),b("a present","プレゼントを","目的語")],
 "jp":"私は彼にプレゼントをあげた。","point":"give+人+物（人→物の順）",
 "explain":"「彼に→プレゼントを→あげた」→英語は「gave→him→a present」。動詞の後に〈人→物〉。"},
{"level":"発展","pattern":"SVOC(A+B)","en":"We call him Tom.",
 "blocks":[b("We","私たちは","主語"),b("call","呼ぶ","動詞"),b("him","彼を","目的語"),b("Tom","トムと","補語")],
 "jp":"私たちは彼をトムと呼ぶ。","point":"call+A+B=「AをBと呼ぶ」",
 "explain":"「彼を→トムと→呼ぶ」→英語は「call→him→Tom」。〈動詞→A→B〉。"},
{"level":"発展","pattern":"think that ~","en":"I think that he is right.",
 "blocks":[b("I","私は","主語"),b("think","思う","動詞"),b("that","―","その他"),b("he is right","彼は正しい","その他")],
 "jp":"私は彼が正しいと思う。","point":"think (that)+文=「~と思う」",
 "explain":"「彼が正しい→と思う」→英語は「think→(that)→he is right」。「思う」が先、内容が後ろ。that は省略可。"},
{"level":"発展","pattern":"接続詞 when","en":"When I was young, I lived in Osaka.",
 "blocks":[b("When","〜のとき","その他"),b("I was young","私は若かった","その他"),b("I lived","私は住んでいた","動詞"),b("in Osaka","大阪に","場所")],
 "jp":"若かったとき、私は大阪に住んでいた。","point":"When ~, で2つの文をつなぐ",
 "explain":"「~のとき」は when を前に置く。〈When 節, メインの文〉の形。"},
{"level":"発展","pattern":"受け身(be+過去分詞)","en":"English is spoken in Australia.",
 "blocks":[b("English","英語は","主語"),b("is spoken","話されている","動詞"),b("in Australia","オーストラリアで","場所")],
 "jp":"英語はオーストラリアで話されている。","point":"受け身 be+過去分詞=「~される」",
 "explain":"「話されている」=is spoken（be+過去分詞）。主語は動作を受ける側になる。"},
{"level":"発展","pattern":"現在完了(経験)","en":"I have visited Kyoto twice.",
 "blocks":[b("I","私は","主語"),b("have visited","訪れたことがある","動詞"),b("Kyoto","京都を","目的語"),b("twice","2回","時")],
 "jp":"私は京都を2回訪れたことがある。","point":"have+過去分詞=「~したことがある」",
 "explain":"「訪れたことがある」=have visited。経験を表す現在完了。"},
{"level":"発展","pattern":"現在完了(継続)","en":"I have known him for ten years.",
 "blocks":[b("I","私は","主語"),b("have known","知っている","動詞"),b("him","彼を","目的語"),b("for ten years","10年間","時")],
 "jp":"私は彼を10年間知っている。","point":"have+過去分詞=「ずっと~している」(継続)",
 "explain":"「10年間→知っている」→英語は「have known→him→for ten years」。for+期間。"},
{"level":"発展","pattern":"関係代名詞(主格)","en":"I have a friend who lives in Osaka.",
 "blocks":[b("I","私は","主語"),b("have","いる","動詞"),b("a friend","友達が","目的語"),b("who lives in Osaka","大阪に住んでいる","その他")],
 "jp":"私には大阪に住んでいる友達がいる。","point":"名詞+who+説明（後ろから修飾）",
 "explain":"日本語は「大阪に住んでいる→友達」と前から説明。英語は「a friend→who lives in Osaka」で後ろから。語順が真逆の重要ポイント。"},
{"level":"発展","pattern":"関係代名詞(目的格)","en":"This is the book that I bought yesterday.",
 "blocks":[b("This","これは","主語"),b("is","だ","動詞"),b("the book","本","補語"),b("that I bought yesterday","私が昨日買った","その他")],
 "jp":"これは私が昨日買った本だ。","point":"名詞+that+説明（目的格、省略可）",
 "explain":"「私が昨日買った→本」→英語は「the book→that I bought yesterday」。説明が名詞の後ろ。"},
{"level":"発展","pattern":"分詞(後置修飾)","en":"The boy running in the park is my brother.",
 "blocks":[b("The boy","その少年は","主語"),b("running in the park","公園で走っている","その他"),b("is","だ","動詞"),b("my brother","私の弟","補語")],
 "jp":"公園で走っている少年は私の弟だ。","point":"名詞+~ing…=「~している(名詞)」(後置修飾)",
 "explain":"「公園で走っている→少年」→英語は「The boy→running in the park」。-ing のかたまりが名詞の後ろにくる。"},
{"level":"発展","pattern":"形式主語 it","en":"It is fun to play games.",
 "blocks":[b("It","―","主語"),b("is","だ","動詞"),b("fun","楽しい","補語"),b("to play games","ゲームをするのは","その他")],
 "jp":"ゲームをするのは楽しい。","point":"It is … to ~（本当の主語は to ~）",
 "explain":"「ゲームをするのは→楽しい」→英語は形式主語 It で始め、本当の主語 to play games を後ろに置く。"},
]

# ===== 基本 追加 (12) =====
S += [
{"level":"基本","pattern":"命令文","en":"Open the door.",
 "blocks":[b("Open","開けて","動詞"),b("the door","ドアを","目的語")],
 "jp":"ドアを開けて。","point":"命令文は動詞で始める（主語を言わない）",
 "explain":"「ドアを→開けて」→英語は動詞 Open を文頭に。主語 you は省略する。"},
{"level":"基本","pattern":"否定の命令文","en":"Don't run here.",
 "blocks":[b("Don't","〜するな","その他"),b("run","走る","動詞"),b("here","ここで","場所")],
 "jp":"ここで走らないで。","point":"Don't+動詞の原形=「~するな」",
 "explain":"禁止は Don't を文頭に。「ここで→走るな」→「Don't run→here」。"},
{"level":"基本","pattern":"現在進行形","en":"I am reading a book.",
 "blocks":[b("I","私は","主語"),b("am reading","読んでいる","動詞"),b("a book","本を","目的語")],
 "jp":"私は本を読んでいる。","point":"be動詞+~ing=「~している」",
 "explain":"「読んでいる」は am reading（be+ing）。動詞は2語のかたまりで主語の直後。"},
{"level":"基本","pattern":"現在進行形","en":"She is cooking now.",
 "blocks":[b("She","彼女は","主語"),b("is cooking","料理している","動詞"),b("now","今","時")],
 "jp":"彼女は今料理している。","point":"主語に合わせて is+~ing",
 "explain":"She なので is cooking。時(now)は文末。"},
{"level":"基本","pattern":"過去形(規則)","en":"I played soccer yesterday.",
 "blocks":[b("I","私は","主語"),b("played","した","動詞"),b("soccer","サッカーを","目的語"),b("yesterday","昨日","時")],
 "jp":"私は昨日サッカーをした。","point":"規則動詞は-ed、時は文末",
 "explain":"play→played。「昨日 サッカーを した」→英語は「played→soccer→yesterday」。"},
{"level":"基本","pattern":"過去形(不規則)","en":"I went to Kyoto last week.",
 "blocks":[b("I","私は","主語"),b("went","行った","動詞"),b("to Kyoto","京都へ","場所"),b("last week","先週","時")],
 "jp":"私は先週京都へ行った。","point":"go-went（不規則）、時は最後",
 "explain":"「先週 京都へ 行った」→英語は「went→to Kyoto→last week」。"},
{"level":"基本","pattern":"所有格","en":"This is my bag.",
 "blocks":[b("This","これは","主語"),b("is","だ","動詞"),b("my bag","私のかばん","補語")],
 "jp":"これは私のかばんだ。","point":"所有格 my は名詞の前（my bag）",
 "explain":"「私の→かばん」は my+名詞でひとかたまり。日本語と同じ順。"},
{"level":"基本","pattern":"複数形","en":"I have two dogs.",
 "blocks":[b("I","私は","主語"),b("have","飼っている","動詞"),b("two dogs","2匹の犬を","目的語")],
 "jp":"私は2匹の犬を飼っている。","point":"2つ以上は複数形(-s)",
 "explain":"数(two)+複数形(dogs)。「2匹の犬を→飼っている」→「have→two dogs」。"},
{"level":"基本","pattern":"be動詞の疑問文","en":"Is this your pen?",
 "blocks":[b("Is","ですか","動詞"),b("this","これは","主語"),b("your pen","あなたのペン","補語")],
 "jp":"これはあなたのペンですか？","point":"be動詞の疑問文は Is/Are を文頭に",
 "explain":"日本語の「~ですか?」は文末。英語は be動詞 Is を主語の前（文頭）に出す。"},
{"level":"基本","pattern":"疑問詞 What","en":"What is this?",
 "blocks":[b("What","何","疑問"),b("is","です","動詞"),b("this","これは","主語")],
 "jp":"これは何ですか？","point":"What+be動詞+主語",
 "explain":"「これは→何?」→英語は What を文頭に〈What→is→this〉。"},
{"level":"基本","pattern":"疑問詞 Who","en":"Who is that boy?",
 "blocks":[b("Who","だれ","疑問"),b("is","です","動詞"),b("that boy","あの少年は","主語")],
 "jp":"あの少年はだれですか？","point":"Who=だれ、文頭に置く",
 "explain":"「あの少年は→だれ?」→英語は Who を文頭に。"},
{"level":"基本","pattern":"How many+名詞","en":"How many books do you have?",
 "blocks":[b("How many books","何冊の本を","疑問"),b("do","―","助動詞"),b("you","あなたは","主語"),b("have","持っている","動詞")],
 "jp":"あなたは何冊の本を持っていますか？","point":"How many+名詞 を文頭に",
 "explain":"「何冊の本を→持っている?」→「How many books」をひとかたまりで文頭に。"},
]

# ===== 応用 追加 (24) =====
S += [
{"level":"応用","pattern":"be going to","en":"I am going to study tonight.",
 "blocks":[b("I","私は","主語"),b("am going to","〜するつもり","助動詞"),b("study","勉強する","動詞"),b("tonight","今夜","時")],
 "jp":"私は今夜勉強するつもりだ。","point":"be going to+原形=未来(~するつもり)",
 "explain":"「今夜→勉強するつもり」→英語は「am going to study→tonight」。"},
{"level":"応用","pattern":"be going to","en":"It is going to rain.",
 "blocks":[b("It","―","主語"),b("is going to","〜しそう","助動詞"),b("rain","雨が降る","動詞")],
 "jp":"雨が降りそうだ。","point":"be going to=「~しそう/するつもり」",
 "explain":"天気の It を主語に。is going to rain で「降りそう」。"},
{"level":"応用","pattern":"過去進行形","en":"I was watching TV then.",
 "blocks":[b("I","私は","主語"),b("was watching","見ていた","動詞"),b("TV","テレビを","目的語"),b("then","そのとき","時")],
 "jp":"私はそのときテレビを見ていた。","point":"was/were+~ing=過去進行形",
 "explain":"「見ていた」は was watching。時(then)は文末。"},
{"level":"応用","pattern":"過去進行形","en":"They were playing soccer.",
 "blocks":[b("They","彼らは","主語"),b("were playing","していた","動詞"),b("soccer","サッカーを","目的語")],
 "jp":"彼らはサッカーをしていた。","point":"複数主語は were+~ing",
 "explain":"They なので were playing。"},
{"level":"応用","pattern":"不定詞(形容詞的)","en":"I want something to drink.",
 "blocks":[b("I","私は","主語"),b("want","欲しい","動詞"),b("something","何か","目的語"),b("to drink","飲むための","その他")],
 "jp":"私は何か飲み物が欲しい。","point":"名詞+to+原形=「~するための」(後ろから修飾)",
 "explain":"「飲むための→何か」→英語は「something→to drink」。to不定詞が名詞の後ろにくる。"},
{"level":"応用","pattern":"不定詞(形容詞的)","en":"I have a lot of work to do.",
 "blocks":[b("I","私は","主語"),b("have","ある","動詞"),b("a lot of work","たくさんの仕事が","目的語"),b("to do","やるべき","その他")],
 "jp":"私にはやるべき仕事がたくさんある。","point":"名詞+to+原形=「~すべき(名詞)」",
 "explain":"「やるべき→仕事」→英語は「work→to do」。to不定詞が後ろから説明。"},
{"level":"応用","pattern":"不定詞(副詞的・感情)","en":"I am glad to see you.",
 "blocks":[b("I","私は","主語"),b("am","―","動詞"),b("glad","うれしい","補語"),b("to see you","あなたに会えて","その他")],
 "jp":"私はあなたに会えてうれしい。","point":"形容詞+to ~=「~して(感情の原因)」",
 "explain":"「会えて→うれしい」→英語は「glad→to see you」。感情の原因を to ~ で後ろに。"},
{"level":"応用","pattern":"不定詞(名詞的)","en":"I hope to see you again.",
 "blocks":[b("I","私は","主語"),b("hope","願う","動詞"),b("to see you again","また会うことを","目的語")],
 "jp":"私はまたあなたに会いたい。","point":"hope to+原形=「~したいと願う」",
 "explain":"「また会うことを→願う」→英語は「hope→to see you again」。"},
{"level":"応用","pattern":"動名詞","en":"I enjoy reading books.",
 "blocks":[b("I","私は","主語"),b("enjoy","楽しむ","動詞"),b("reading books","本を読むことを","目的語")],
 "jp":"私は本を読むのを楽しむ。","point":"enjoy+~ing（動名詞）",
 "explain":"enjoy の後は ~ing。「読むことを→楽しむ」→「enjoy→reading books」。"},
{"level":"応用","pattern":"動名詞(前置詞の後)","en":"He is good at playing soccer.",
 "blocks":[b("He","彼は","主語"),b("is good at","得意だ","動詞"),b("playing soccer","サッカーをすることが","その他")],
 "jp":"彼はサッカーが得意だ。","point":"前置詞(at)の後は~ing",
 "explain":"be good at の後は動名詞。「サッカーをすることが→得意」→「good at→playing soccer」。"},
{"level":"応用","pattern":"動名詞(前置詞の後)","en":"Thank you for helping me.",
 "blocks":[b("Thank you","ありがとう","その他"),b("for helping me","助けてくれて","その他")],
 "jp":"助けてくれてありがとう。","point":"for+~ing=「~してくれて」",
 "explain":"前置詞 for の後は動名詞。「助けてくれて→ありがとう」→「Thank you→for helping me」。"},
{"level":"応用","pattern":"動名詞(目的語)","en":"Please stop talking.",
 "blocks":[b("Please","お願い","その他"),b("stop","やめて","動詞"),b("talking","話すのを","目的語")],
 "jp":"話すのをやめてください。","point":"stop+~ing=「~するのをやめる」",
 "explain":"stop の後は ~ing。「話すのを→やめて」→「stop→talking」。"},
{"level":"応用","pattern":"動名詞(主語)","en":"Reading books is fun.",
 "blocks":[b("Reading books","本を読むことは","主語"),b("is","だ","動詞"),b("fun","楽しい","補語")],
 "jp":"本を読むことは楽しい。","point":"~ing が主語=「~することは」",
 "explain":"動名詞が文の主語に。「本を読むことは→楽しい」→「Reading books→is fun」。"},
{"level":"応用","pattern":"接続詞 if","en":"If you are free, call me.",
 "blocks":[b("If","もし〜なら","その他"),b("you are free","あなたが暇","その他"),b("call me","電話して","その他")],
 "jp":"もし暇なら、電話して。","point":"if ~=「もし~なら」(条件)",
 "explain":"条件は if を前に。〈If 節, メインの文〉。"},
{"level":"応用","pattern":"接続詞 because","en":"I was late because I missed the bus.",
 "blocks":[b("I was late","私は遅れた","その他"),b("because","〜だから","その他"),b("I missed the bus","バスに乗り遅れた","その他")],
 "jp":"バスに乗り遅れたので、私は遅れた。","point":"because ~=「~だから」(理由)",
 "explain":"理由は because でつなぐ。〈結果 + because + 理由〉の語順。"},
{"level":"応用","pattern":"as ~ as","en":"I am as tall as you.",
 "blocks":[b("I","私は","主語"),b("am","―","動詞"),b("as tall as","同じくらい背が高い","補語"),b("you","あなたと","その他")],
 "jp":"私はあなたと同じくらい背が高い。","point":"as+原級+as=「…と同じくらい~」",
 "explain":"「あなたと→同じくらい高い」→英語は「as tall as→you」。as ... as で挟む。"},
{"level":"応用","pattern":"not as ~ as","en":"This is not as big as that.",
 "blocks":[b("This","これは","主語"),b("is not","〜でない","動詞"),b("as big as","〜ほど大きく","補語"),b("that","あれ","その他")],
 "jp":"これはあれほど大きくない。","point":"not as ~ as=「…ほど~でない」",
 "explain":"「あれ→ほど大きくない」→「not as big as→that」。"},
{"level":"応用","pattern":"SVC(look+形容詞)","en":"You look tired.",
 "blocks":[b("You","あなたは","主語"),b("look","見える","動詞"),b("tired","疲れて","補語")],
 "jp":"あなたは疲れて見える。","point":"look+形容詞=「~に見える」",
 "explain":"「疲れて→見える」→英語は「look→tired」。look の後に形容詞。"},
{"level":"応用","pattern":"SVC(become)","en":"He became a doctor.",
 "blocks":[b("He","彼は","主語"),b("became","なった","動詞"),b("a doctor","医者に","補語")],
 "jp":"彼は医者になった。","point":"become+名詞=「~になる」",
 "explain":"「医者に→なった」→英語は「became→a doctor」。"},
{"level":"応用","pattern":"SVOO(物+to+人)","en":"I gave a present to him.",
 "blocks":[b("I","私は","主語"),b("gave","あげた","動詞"),b("a present","プレゼントを","目的語"),b("to him","彼に","場所")],
 "jp":"私は彼にプレゼントをあげた。","point":"give+物+to+人 の形もある",
 "explain":"「彼に プレゼントを あげた」は give him a present のほか、give a present to him とも言える。"},
{"level":"応用","pattern":"疑問詞 When","en":"When do you study?",
 "blocks":[b("When","いつ","疑問"),b("do","―","助動詞"),b("you","あなたは","主語"),b("study","勉強する","動詞")],
 "jp":"あなたはいつ勉強しますか？","point":"When を文頭に→do→主語→動詞",
 "explain":"「いつ→勉強する?」→英語は When を文頭に〈When→do→you→study〉。"},
{"level":"応用","pattern":"疑問詞 How","en":"How do you go to school?",
 "blocks":[b("How","どうやって","疑問"),b("do","―","助動詞"),b("you","あなたは","主語"),b("go","行く","動詞"),b("to school","学校へ","場所")],
 "jp":"あなたはどうやって学校へ行きますか？","point":"How(手段)を文頭に",
 "explain":"「どうやって→学校へ→行く?」→「How→do→you→go→to school」。"},
{"level":"応用","pattern":"must not(禁止)","en":"You must not swim here.",
 "blocks":[b("You","あなたは","主語"),b("must not","〜してはいけない","助動詞"),b("swim","泳ぐ","動詞"),b("here","ここで","場所")],
 "jp":"ここで泳いではいけない。","point":"must not=「~してはいけない」(強い禁止)",
 "explain":"「ここで→泳いではいけない」→「must not swim→here」。"},
{"level":"応用","pattern":"don't have to(不要)","en":"You don't have to come.",
 "blocks":[b("You","あなたは","主語"),b("don't have to","〜しなくてよい","助動詞"),b("come","来る","動詞")],
 "jp":"あなたは来なくてよい。","point":"don't have to=「~しなくてよい」(不要)",
 "explain":"must not(禁止)と違い、don't have to は「する必要がない」。"},
]

# ===== 発展 追加 (34) =====
S += [
{"level":"発展","pattern":"受け身(過去)","en":"This temple was built long ago.",
 "blocks":[b("This temple","この寺は","主語"),b("was built","建てられた","動詞"),b("long ago","ずっと昔に","時")],
 "jp":"この寺はずっと昔に建てられた。","point":"was/were+過去分詞=過去の受け身",
 "explain":"「建てられた」は was built。主語は動作を受ける側。時は文末。"},
{"level":"発展","pattern":"受け身(by)","en":"This song is loved by everyone.",
 "blocks":[b("This song","この歌は","主語"),b("is loved","愛されている","動詞"),b("by everyone","みんなに","その他")],
 "jp":"この歌はみんなに愛されている。","point":"by ~=「~によって」(動作主)",
 "explain":"「みんなに→愛されている」→英語は「is loved→by everyone」。by の後に動作主。"},
{"level":"発展","pattern":"受け身(疑問)","en":"Was this book written by him?",
 "blocks":[b("Was","―","助動詞"),b("this book","この本は","主語"),b("written","書かれた","動詞"),b("by him","彼によって","その他")],
 "jp":"この本は彼によって書かれたのですか？","point":"受け身の疑問は be動詞を文頭に",
 "explain":"受け身の疑問文は Was/Is を主語の前へ。〈Was→主語→過去分詞→by ~〉。"},
{"level":"発展","pattern":"現在完了(完了・just)","en":"I have just finished lunch.",
 "blocks":[b("I","私は","主語"),b("have just finished","ちょうど終えた","動詞"),b("lunch","昼食を","目的語")],
 "jp":"私はちょうど昼食を終えた。","point":"have just+過去分詞=「ちょうど~した」",
 "explain":"完了を表す現在完了。just(ちょうど)を have と過去分詞の間に。"},
{"level":"発展","pattern":"現在完了(完了・already)","en":"I have already read it.",
 "blocks":[b("I","私は","主語"),b("have already read","もう読んだ","動詞"),b("it","それを","目的語")],
 "jp":"私はもうそれを読んだ。","point":"already=「もう・すでに」(完了)",
 "explain":"「もう読んだ」=have already read。"},
{"level":"発展","pattern":"現在完了(完了・yet)","en":"I haven't done it yet.",
 "blocks":[b("I","私は","主語"),b("haven't done","まだしていない","動詞"),b("it","それを","目的語"),b("yet","まだ","時")],
 "jp":"私はまだそれをしていない。","point":"not ~ yet=「まだ~していない」",
 "explain":"否定文の yet は文末で「まだ」。"},
{"level":"発展","pattern":"have been to","en":"I have been to Hokkaido.",
 "blocks":[b("I","私は","主語"),b("have been to","行ったことがある","動詞"),b("Hokkaido","北海道へ","場所")],
 "jp":"私は北海道へ行ったことがある。","point":"have been to ~=「~へ行ったことがある」",
 "explain":"経験を表す。have gone to(行ってしまった)とは意味が違う。"},
{"level":"発展","pattern":"現在完了進行形","en":"I have been studying for two hours.",
 "blocks":[b("I","私は","主語"),b("have been studying","ずっと勉強している","動詞"),b("for two hours","2時間","時")],
 "jp":"私は2時間ずっと勉強している。","point":"have been+~ing=「ずっと~し続けている」",
 "explain":"動作の継続。「2時間→勉強し続けている」→「have been studying→for two hours」。"},
{"level":"発展","pattern":"形式主語 it...to","en":"It is important to read books.",
 "blocks":[b("It","―","主語"),b("is","だ","動詞"),b("important","大切","補語"),b("to read books","本を読むことは","その他")],
 "jp":"本を読むことは大切だ。","point":"It is … to ~（本当の主語は to ~）",
 "explain":"「本を読むことは→大切」→形式主語 It で始め、本当の主語 to read books を後ろに。"},
{"level":"発展","pattern":"too ... to","en":"This box is too heavy to carry.",
 "blocks":[b("This box","この箱は","主語"),b("is","―","動詞"),b("too heavy","重すぎる","補語"),b("to carry","運ぶには","その他")],
 "jp":"この箱は重すぎて運べない。","point":"too ... to ~=「~するには…すぎる」",
 "explain":"「運ぶには→重すぎる」→「too heavy→to carry」。"},
{"level":"発展","pattern":"want+人+to","en":"I want you to help me.",
 "blocks":[b("I","私は","主語"),b("want","してほしい","動詞"),b("you","あなたに","目的語"),b("to help me","私を助けて","その他")],
 "jp":"私はあなたに助けてほしい。","point":"want+人+to+原形=「人に~してほしい」",
 "explain":"「あなたに→助けてほしい」→英語は「want→you→to help me」。〈動詞→人→to+原形〉。"},
{"level":"発展","pattern":"tell+人+to","en":"She told me to wait.",
 "blocks":[b("She","彼女は","主語"),b("told","言った","動詞"),b("me","私に","目的語"),b("to wait","待つように","その他")],
 "jp":"彼女は私に待つように言った。","point":"tell+人+to+原形=「人に~するよう言う」",
 "explain":"「私に→待つように→言った」→「told→me→to wait」。"},
{"level":"発展","pattern":"ask+人+to","en":"I asked him to come.",
 "blocks":[b("I","私は","主語"),b("asked","頼んだ","動詞"),b("him","彼に","目的語"),b("to come","来るように","その他")],
 "jp":"私は彼に来るように頼んだ。","point":"ask+人+to+原形=「人に~を頼む」",
 "explain":"「彼に→来るように→頼んだ」→「asked→him→to come」。"},
{"level":"発展","pattern":"疑問詞+to(how to)","en":"I know how to swim.",
 "blocks":[b("I","私は","主語"),b("know","知っている","動詞"),b("how to swim","泳ぎ方を","目的語")],
 "jp":"私は泳ぎ方を知っている。","point":"how to+原形=「~の仕方」",
 "explain":"how to swim でひとかたまり「泳ぎ方」。"},
{"level":"発展","pattern":"疑問詞+to(what to)","en":"I don't know what to do.",
 "blocks":[b("I","私は","主語"),b("don't know","わからない","動詞"),b("what to do","何をすべきか","目的語")],
 "jp":"私は何をすべきかわからない。","point":"what to ~=「何を~すべきか」",
 "explain":"what to do でひとかたまり「何をすべきか」。"},
{"level":"発展","pattern":"分詞(現在分詞・前置)","en":"Look at the sleeping baby.",
 "blocks":[b("Look at","見て","動詞"),b("the sleeping baby","眠っている赤ちゃんを","目的語")],
 "jp":"眠っている赤ちゃんを見て。","point":"分詞1語は名詞の前(sleeping baby)",
 "explain":"「眠っている→赤ちゃん」。1語の分詞は名詞の前。長い説明は後ろから（次の文と比較）。"},
{"level":"発展","pattern":"分詞(過去分詞・前置)","en":"This is a used car.",
 "blocks":[b("This","これは","主語"),b("is","だ","動詞"),b("a used car","中古車","補語")],
 "jp":"これは中古車だ。","point":"過去分詞1語も名詞の前(used car=使われた車)",
 "explain":"used(使われた)が car を前から修飾して「中古車」。"},
{"level":"発展","pattern":"分詞(過去分詞・後置)","en":"This is a book written by him.",
 "blocks":[b("This","これは","主語"),b("is","だ","動詞"),b("a book","本","補語"),b("written by him","彼によって書かれた","その他")],
 "jp":"これは彼によって書かれた本だ。","point":"名詞+過去分詞…=後ろから「~された」と修飾",
 "explain":"「彼によって書かれた→本」→英語は「a book→written by him」。分詞のかたまりが名詞の後ろ。語順が逆。"},
{"level":"発展","pattern":"分詞(過去分詞・後置)","en":"The language spoken here is English.",
 "blocks":[b("The language","言語は","主語"),b("spoken here","ここで話されている","その他"),b("is","だ","動詞"),b("English","英語","補語")],
 "jp":"ここで話されている言語は英語だ。","point":"名詞+過去分詞=後置修飾",
 "explain":"「ここで話されている→言語」→「The language→spoken here」。主語を後ろから説明。"},
{"level":"発展","pattern":"分詞(現在分詞・後置)","en":"Look at the boy playing tennis.",
 "blocks":[b("Look at","見て","動詞"),b("the boy","少年を","目的語"),b("playing tennis","テニスをしている","その他")],
 "jp":"テニスをしている少年を見て。","point":"名詞+~ing=後ろから修飾",
 "explain":"「テニスをしている→少年」→「the boy→playing tennis」。"},
{"level":"発展","pattern":"関係代名詞(主格 which)","en":"This is a train which goes to Tokyo.",
 "blocks":[b("This","これは","主語"),b("is","だ","動詞"),b("a train","電車","補語"),b("which goes to Tokyo","東京へ行く","その他")],
 "jp":"これは東京へ行く電車だ。","point":"which(もの)+動詞=主格の関係代名詞",
 "explain":"「東京へ行く→電車」→英語は「a train→which goes to Tokyo」。説明が名詞の後ろ。"},
{"level":"発展","pattern":"関係代名詞(主格 that)","en":"I know a boy that can run fast.",
 "blocks":[b("I","私は","主語"),b("know","知っている","動詞"),b("a boy","少年を","目的語"),b("that can run fast","速く走れる","その他")],
 "jp":"私は速く走れる少年を知っている。","point":"that は人にも物にも使える(主格)",
 "explain":"「速く走れる→少年」→「a boy→that can run fast」。"},
{"level":"発展","pattern":"関係代名詞(目的格 which)","en":"The book which I read was fun.",
 "blocks":[b("The book","本は","主語"),b("which I read","私が読んだ","その他"),b("was","だった","動詞"),b("fun","おもしろい","補語")],
 "jp":"私が読んだ本はおもしろかった。","point":"目的格 which(+主語+動詞)。省略可",
 "explain":"「私が読んだ→本」→「The book→which I read」。主語を後ろから説明。"},
{"level":"発展","pattern":"接触節(関係代名詞の省略)","en":"The cake you made was great.",
 "blocks":[b("The cake","ケーキは","主語"),b("you made","あなたが作った","その他"),b("was","だった","動詞"),b("great","すばらしい","補語")],
 "jp":"あなたが作ったケーキはすばらしかった。","point":"目的格の関係代名詞は省略できる(接触節)",
 "explain":"「あなたが作った→ケーキ」→英語は「The cake→you made」。that/which を省き、名詞のすぐ後に〈主語+動詞〉。"},
{"level":"発展","pattern":"関係代名詞(目的格 who)","en":"The man who I met was kind.",
 "blocks":[b("The man","男性は","主語"),b("who I met","私が会った","その他"),b("was","だった","動詞"),b("kind","親切","補語")],
 "jp":"私が会った男性は親切だった。","point":"人の目的格は who(m)/that",
 "explain":"「私が会った→男性」→「The man→who I met」。"},
{"level":"発展","pattern":"間接疑問(where)","en":"I don't know where he lives.",
 "blocks":[b("I","私は","主語"),b("don't know","わからない","動詞"),b("where","どこに","疑問"),b("he","彼が","主語"),b("lives","住んでいるか","動詞")],
 "jp":"私は彼がどこに住んでいるかわからない。","point":"間接疑問は〈疑問詞+主語+動詞〉(ふつうの語順)",
 "explain":"Where does he live? が文中に入ると where he lives に。do が消え、主語+動詞の順に戻る。"},
{"level":"発展","pattern":"間接疑問(what)","en":"Tell me what you want.",
 "blocks":[b("Tell me","教えて","動詞"),b("what","何が","疑問"),b("you","あなたが","主語"),b("want","欲しいか","動詞")],
 "jp":"何が欲しいか教えて。","point":"what+主語+動詞",
 "explain":"What do you want? → what you want。疑問詞の後は主語+動詞。"},
{"level":"発展","pattern":"間接疑問(who)","en":"Do you know who that man is?",
 "blocks":[b("Do you know","知っていますか","動詞"),b("who","だれか","疑問"),b("that man","あの男性が","主語"),b("is","である","動詞")],
 "jp":"あの男性がだれか知っていますか？","point":"who+主語+動詞(is は最後)",
 "explain":"Who is that man? が文中で who that man is に。動詞 is が後ろに回る。"},
{"level":"発展","pattern":"仮定法(if)","en":"If I were a bird, I could fly.",
 "blocks":[b("If","もし","その他"),b("I","私が","主語"),b("were","〜だったら","動詞"),b("a bird","鳥","補語"),b("I","私は","主語"),b("could fly","飛べるのに","動詞")],
 "jp":"もし私が鳥だったら、飛べるのに。","point":"If 主語 were ~, 主語 could …（現実と違う仮定）",
 "explain":"現実に反する仮定。be動詞は主語に関係なく were、後半は could/would+原形。"},
{"level":"発展","pattern":"仮定法(I wish)","en":"I wish I could fly.",
 "blocks":[b("I wish","〜ならいいのに","その他"),b("I","私が","主語"),b("could fly","飛べたら","動詞")],
 "jp":"飛べたらいいのに。","point":"I wish 主語 could ~=「~できたらいいのに」",
 "explain":"実現しない願望。wish の後は could/過去形を使う。"},
{"level":"発展","pattern":"感嘆文(What)","en":"What a beautiful flower!",
 "blocks":[b("What","なんて","疑問"),b("a beautiful flower","美しい花なんだ","補語")],
 "jp":"なんて美しい花なんだ！","point":"What a+形容詞+名詞!=「なんて~な…!」",
 "explain":"感動を表す。What a の後に〈形容詞+名詞〉。"},
{"level":"発展","pattern":"感嘆文(How)","en":"How beautiful it is!",
 "blocks":[b("How","なんて","疑問"),b("beautiful","美しい","補語"),b("it is","それは","主語")],
 "jp":"それはなんて美しいんだ！","point":"How+形容詞+主語+動詞!",
 "explain":"How の後は形容詞(または副詞)。What a ~ との違いに注意。"},
{"level":"発展","pattern":"付加疑問","en":"You like music, don't you?",
 "blocks":[b("You like music","音楽が好きだよね","その他"),b("don't you","ですよね","疑問")],
 "jp":"あなたは音楽が好きですよね？","point":"肯定文,+否定の短縮形?=「~ですよね」",
 "explain":"確認の付加疑問。肯定文には don't you? のように否定形を付ける。"},
{"level":"発展","pattern":"原形不定詞(help)","en":"I helped him cook.",
 "blocks":[b("I","私は","主語"),b("helped","手伝った","動詞"),b("him","彼が","目的語"),b("cook","料理するのを","その他")],
 "jp":"私は彼が料理するのを手伝った。","point":"help+人+原形=「人が~するのを手伝う」",
 "explain":"help の後は to なしの原形でもよい。「彼が→料理するのを→手伝った」→「helped→him→cook」。"},
]

# ===== 検証 =====
ROLES = {"主語","動詞","目的語","補語","場所","時","助動詞","疑問","その他"}
LEVELS = {"基本","応用","発展"}
def norm(s): return re.sub(r"\s+"," ", re.sub(r"[.,?!]", "", s)).strip().lower()

errors=[]
S.sort(key=lambda q:{"基本":0,"応用":1,"発展":2}[q["level"]])  # stable: group by level, keep insertion order within
for i,q in enumerate(S):
    q["id"]=i+1
    tag=f"[id{q['id']} {q['en']!r}]"
    for f in ("level","pattern","en","blocks","jp","point","explain"):
        if f not in q or not q[f]: errors.append(f"{tag} missing/empty '{f}'")
    if q.get("level") not in LEVELS: errors.append(f"{tag} bad level {q.get('level')}")
    # blocks reconstruct the english sentence (order check!)
    joined=norm(" ".join(bl["en"] for bl in q["blocks"]))
    if joined != norm(q["en"]):
        errors.append(f"{tag} blocks!=en\n     blocks:{joined}\n     en    :{norm(q['en'])}")
    for bl in q["blocks"]:
        if not bl.get("en") or not bl.get("jp"): errors.append(f"{tag} empty block {bl}")
        if bl.get("role") not in ROLES: errors.append(f"{tag} bad role {bl.get('role')}")

from collections import Counter
print(f"Total sentences: {len(S)}")
print("By level:", dict(Counter(q['level'] for q in S)))
print("Avg blocks/sentence:", round(sum(len(q['blocks']) for q in S)/len(S),1))
print("Role usage:", dict(Counter(bl['role'] for q in S for bl in q['blocks'])))
print()
if errors:
    print(f"❌ {len(errors)} ISSUE(S):")
    for e in errors: print("  -",e)
    sys.exit(1)
else:
    print("✅ ALL CHECKS PASSED (structure + block→sentence reconstruction)")
    json.dump(S, open("sentences.json","w",encoding="utf-8"), ensure_ascii=False, indent=1)
    print("→ wrote sentences.json")
